#ifndef _CHOCOLATE_KEEN_CONFIG_
#define _CHOCOLATE_KEEN_CONFIG_

#include "SDL.h"

// Pick some sane defaults for the launcher UI
#if SDL_VERSION_ATLEAST(2,0,0)
#define CHOCOLATE_KEEN_LAUNCHER_UI_OUTPUTSYS OUTPUTSYS_TEXTURE
#else
#define CHOCOLATE_KEEN_LAUNCHER_UI_OUTPUTSYS OUTPUTSYS_SURFACE
#endif

// GL stuff
#ifdef _CHOCOLATE_KEEN_ENABLE_OPENGL_

#define _CHOCOLATE_KEEN_HAVE_OPENGL_1_1_ 1
#define _CHOCOLATE_KEEN_HAVE_OPENGL_2_0_ 1
#if SDL_VERSION_ATLEAST(2,0,0)
#define _CHOCOLATE_KEEN_HAVE_OPENGL_ES_2_0_ 1
#endif

// Better don't touch this
#if (defined _CHOCOLATE_KEEN_HAVE_OPENGL_2_0_) || (defined _CHOCOLATE_KEEN_HAVE_OPENGL_ES_2_0_)
#define _CHOCOLATE_KEEN_HAVE_OPENGL_2_0_ANY_ 1
#endif

#if (defined _CHOCOLATE_KEEN_HAVE_OPENGL_2_0_) || (defined _CHOCOLATE_KEEN_HAVE_OPENGL_1_1_)
#define _CHOCOLATE_KEEN_HAVE_OPENGL_DESKTOP_ANY_ 1
#endif

#endif // _CHOCOLATE_KEEN_ENABLE_OPENGL_

#endif
