// input_keys.c: Implements input keys for the input subsystem.

#include "input/input_keys.h"

// Keep this table in lock-step with EmulatedKeyIndex_T.
// A compile-time size check right below enforces matching entry counts.
const EmulatedKey_T engine_emulatedKeysTable[] = {
    {"key_esc", 1},
    {"key_f1", 0x3b},
    {"key_f2", 0x3c},
    {"key_f3", 0x3d},
    {"key_f4", 0x3e},
    {"key_f5", 0x3f},
    {"key_f6", 0x40},
    {"key_f7", 0x41},
    {"key_f8", 0x42},
    {"key_f9", 0x43},
    {"key_f10", 0x44},
    {"key_f11", 0x57},
    {"key_f12", 0x58},
    {"key_grave", 0x29},
    {"key_1", 2},
    {"key_2", 3},
    {"key_3", 4},
    {"key_4", 5},
    {"key_5", 6},
    {"key_6", 7},
    {"key_7", 8},
    {"key_8", 9},
    {"key_9", 0xa},
    {"key_0", 0xb},
    {"key_minus", 0xc},
    {"key_equals", 0xd},
    {"key_bspace", 0xe},
    {"key_tab", 0xf},
    {"key_q", 0x10},
    {"key_w", 0x11},
    {"key_e", 0x12},
    {"key_r", 0x13},
    {"key_t", 0x14},
    {"key_y", 0x15},
    {"key_u", 0x16},
    {"key_i", 0x17},
    {"key_o", 0x18},
    {"key_p", 0x19},
    {"key_lbracket", 0x1a},
    {"key_rbracket", 0x1b},
    {"key_enter", 0x1c},
    {"key_capslock", 0x3a},
    {"key_a", 0x1e},
    {"key_s", 0x1f},
    {"key_d", 0x20},
    {"key_f", 0x21},
    {"key_g", 0x22},
    {"key_h", 0x23},
    {"key_j", 0x24},
    {"key_k", 0x25},
    {"key_l", 0x26},
    {"key_semicolon", 0x27},
    {"key_quote", 0x28},
    {"key_backslash", 0x2b},
    {"key_lshift", 0x2a},
    {"key_lessthan", 0x56},
    {"key_z", 0x2c},
    {"key_x", 0x2d},
    {"key_c", 0x2e},
    {"key_v", 0x2f},
    {"key_b", 0x30},
    {"key_n", 0x31},
    {"key_m", 0x32},
    {"key_comma", 0x33},
    {"key_period", 0x34},
    {"key_slash", 0x35},
    {"key_rshift", 0x36},
    {"key_lctrl", 0x1d},
    {"key_lalt", 0x38},
    {"key_space", 0x39},
    {"key_ralt", 0x38},
    {"key_rctrl", 0x1d},
    {"key_printscreen", 0x37}, // SPECIAL (and same scancode as key_kp_multiply)
    {"key_scrolllock", 0x40},
    {"key_pause", 0x1d}, // SPECIAL (and shares a scancode with the control keys)
    {"key_insert", 0x52},
    {"key_home", 0x47},
    {"key_pageup", 0x49},
    {"key_delete", 0x53},
    {"key_end", 0x4f},
    {"key_pagedown", 0x51},
    {"key_up", 0x48},
    {"key_left", 0x4b},
    {"key_down", 0x50},
    {"key_right", 0x4d},
    {"key_numlock", 0x45},
    {"key_kp_divide", 0x35},
    {"key_kp_multiply", 0x37},
    {"key_kp_minus", 0x4a},
    {"key_kp_7", 0x47},
    {"key_kp_8", 0x48},
    {"key_kp_9", 0x49},
    {"key_kp_plus", 0x4e},
    {"key_kp_4", 0x4b},
    {"key_kp_5", 0x4c},
    {"key_kp_6", 0x4d},
    {"key_kp_1", 0x4f},
    {"key_kp_2", 0x50},
    {"key_kp_3", 0x51},
    {"key_kp_enter", 0x1c},
    {"key_kp_0", 0x52},
    {"key_kp_period", 0x53},
};

typedef char EmulatedKeysTableSizeMustMatchEnumCount[
    (sizeof(engine_emulatedKeysTable)/sizeof(engine_emulatedKeysTable[0]) == EMULATEDKEYINDEX_KEY_INDICES_COUNT) ? 1 : -1
];

const int engine_emulatedKeysTableCount =
    (int)(sizeof(engine_emulatedKeysTable) / sizeof(engine_emulatedKeysTable[0]));
