#include "SDL.h"

#include "input/input_default_mappings.h"

const MappedInputEvent_T defaultKeyMappings[] = {
#if SDL_VERSION_ATLEAST(2,0,0)
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_A, 0}, // SDL_SCANCODE_A
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_B, 0}, // SDL_SCANCODE_B
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_C, 0}, // SDL_SCANCODE_C
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_D, 0}, // SDL_SCANCODE_D
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_E, 0}, // SDL_SCANCODE_E
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F, 0}, // SDL_SCANCODE_F
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_G, 0}, // SDL_SCANCODE_G
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_H, 0}, // SDL_SCANCODE_H
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_I, 0}, // SDL_SCANCODE_I
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_J, 0}, // SDL_SCANCODE_J
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_K, 0}, // SDL_SCANCODE_K
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_L, 0}, // SDL_SCANCODE_L
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_M, 0}, // SDL_SCANCODE_M
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_N, 0}, // SDL_SCANCODE_N
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_O, 0}, // SDL_SCANCODE_O
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_P, 0}, // SDL_SCANCODE_P
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_Q, 0}, // SDL_SCANCODE_Q
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_R, 0}, // SDL_SCANCODE_R
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_S, 0}, // SDL_SCANCODE_S
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_T, 0}, // SDL_SCANCODE_T
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_U, 0}, // SDL_SCANCODE_U
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_V, 0}, // SDL_SCANCODE_V
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_W, 0}, // SDL_SCANCODE_W
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_X, 0}, // SDL_SCANCODE_X
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_Y, 0}, // SDL_SCANCODE_Y
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_Z, 0}, // SDL_SCANCODE_Z

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_1, 0}, // SDL_SCANCODE_1
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_2, 0}, // SDL_SCANCODE_2
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_3, 0}, // SDL_SCANCODE_3
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_4, 0}, // SDL_SCANCODE_4
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_5, 0}, // SDL_SCANCODE_5
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_6, 0}, // SDL_SCANCODE_6
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_7, 0}, // SDL_SCANCODE_7
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_8, 0}, // SDL_SCANCODE_8
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_9, 0}, // SDL_SCANCODE_9
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_0, 0}, // SDL_SCANCODE_0

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_ENTER, 0}, // SDL_SCANCODE_RETURN
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_ESC, 0}, // SDL_SCANCODE_ESCAPE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_BSPACE, 0}, // SDL_SCANCODE_BACKSPACE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_TAB, 0}, // SDL_SCANCODE_TAB
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_SPACE, 0}, // SDL_SCANCODE_SPACE

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_MINUS, 0}, // SDL_SCANCODE_MINUS
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_EQUALS, 0}, // SDL_SCANCODE_EQUALS
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LBRACKET, 0}, // SDL_SCANCODE_LEFTBRACKET
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RBRACKET, 0}, // SDL_SCANCODE_RIGHTBRACKET
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_BACKSLASH, 0}, // SDL_SCANCODE_BACKSLASH

    {EMULATEDINPUT_NONE, 0, 0}, // SDL_SCANCODE_NONUSHASH

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_SEMICOLON, 0}, // SDL_SCANCODE_SEMICOLON
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_QUOTE, 0}, // SDL_SCANCODE_APOSTROPHE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_GRAVE, 0}, // SDL_SCANCODE_GRAVE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_COMMA, 0}, // SDL_SCANCODE_COMMA
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PERIOD, 0}, // SDL_SCANCODE_PERIOD
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_SLASH, 0}, // SDL_SCANCODE_SLASH

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_CAPSLOCK, 0}, // SDL_SCANCODE_CAPSLOCK

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F1, 0}, // SDL_SCANCODE_F1
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F2, 0}, // SDL_SCANCODE_F2
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F3, 0}, // SDL_SCANCODE_F3
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F4, 0}, // SDL_SCANCODE_F4
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F5, 0}, // SDL_SCANCODE_F5
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F6, 0}, // SDL_SCANCODE_F6
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F7, 0}, // SDL_SCANCODE_F7
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F8, 0}, // SDL_SCANCODE_F8
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F9, 0}, // SDL_SCANCODE_F9
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F10, 0}, // SDL_SCANCODE_F10
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F11, 0}, // SDL_SCANCODE_F11
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F12, 0}, // SDL_SCANCODE_F12

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PRINTSCREEN, 0}, // SDL_SCANCODE_PRINTSCREEN
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_SCROLLLOCK, 0}, // SDL_SCANCODE_SCROLLLOCK
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PAUSE, 0}, // SDL_SCANCODE_PAUSE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_INSERT, 0}, // SDL_SCANCODE_INSERT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_HOME, 0}, // SDL_SCANCODE_HOME
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PAGEUP, 0}, // SDL_SCANCODE_PAGEUP
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_DELETE, 0}, // SDL_SCANCODE_DELETE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_END, 0}, // SDL_SCANCODE_END
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PAGEDOWN, 0}, // SDL_SCANCODE_PAGEDOWN
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RIGHT, 0}, // SDL_SCANCODE_RIGHT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LEFT, 0}, // SDL_SCANCODE_LEFT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_DOWN, 0}, // SDL_SCANCODE_DOWN
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_UP, 0}, // SDL_SCANCODE_UP

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_NUMLOCK, 0}, // SDL_SCANCODE_NUMLOCKCLEAR
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_DIVIDE, 0}, // SDL_SCANCODE_KP_DIVIDE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_MULTIPLY, 0}, // SDL_SCANCODE_KP_MULTIPLY
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_MINUS, 0}, // SDL_SCANCODE_KP_MINUS
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_PLUS, 0}, // SDL_SCANCODE_KP_PLUS
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_ENTER, 0}, // SDL_SCANCODE_KP_ENTER
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_1, 0}, // SDL_SCANCODE_KP_1
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_2, 0}, // SDL_SCANCODE_KP_2
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_3, 0}, // SDL_SCANCODE_KP_3
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_4, 0}, // SDL_SCANCODE_KP_4
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_5, 0}, // SDL_SCANCODE_KP_5
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_6, 0}, // SDL_SCANCODE_KP_6
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_7, 0}, // SDL_SCANCODE_KP_7
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_8, 0}, // SDL_SCANCODE_KP_8
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_9, 0}, // SDL_SCANCODE_KP_9
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_0, 0}, // SDL_SCANCODE_KP_0
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_PERIOD, 0}, // SDL_SCANCODE_KP_PERIOD

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LESSTHAN, 0}, // SDL_SCANCODE_NONUSBACKSLASH,

    // SDL 2.0 scancodes 101 to 223 (either actually defined or not) follow...
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LCTRL, 0}, // SDL_SCANCODE_LCTRL
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LSHIFT, 0}, // SDL_SCANCODE_LSHIFT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LALT, 0}, // SDL_SCANCODE_LALT

    {EMULATEDINPUT_NONE, 0, 0}, // SDL_SCANCODE_LGUI

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RCTRL, 0}, // SDL_SCANCODE_RCTRL
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RSHIFT, 0}, // SDL_SCANCODE_RSHIFT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RALT, 0}, // SDL_SCANCODE_RALT

    // A couple of more SDL 2.0 scancodes follow, but are ignored
#else
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_BSPACE, 0}, // SDLK_BACKSPACE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_TAB, 0}, // SDLK_TAB
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_CLEAR
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_ENTER, 0}, // SDLK_RETURN
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PAUSE, 0}, // SDLK_PAUSE
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_ESC, 0}, // SDLK_ESCAPE
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_SPACE, 0}, // SDLK_SPACE
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_EXCLAIM
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_QUOTEDBL
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_HASH
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_DOLLAR
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_AMPERSAND
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_QUOTE, 0}, // SDLK_QUOTE
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_LEFTPAREN
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_RIGHTPAREN
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_ASTERISK
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_PLUS
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_COMMA, 0}, // SDLK_COMMA
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_MINUS, 0}, // SDLK_MINUS
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PERIOD, 0}, // SDLK_PERIOD
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_SLASH, 0}, // SDLK_SLASH
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_0, 0}, // SDLK_0
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_1, 0}, // SDLK_1
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_2, 0}, // SDLK_2
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_3, 0}, // SDLK_3
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_4, 0}, // SDLK_4
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_5, 0}, // SDLK_5
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_6, 0}, // SDLK_6
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_7, 0}, // SDLK_7
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_8, 0}, // SDLK_8
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_9, 0}, // SDLK_9
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_COLON
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_SEMICOLON, 0}, // SDLK_SEMICOLON
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LESSTHAN, 0}, // SDLK_LESS
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_EQUALS, 0}, // SDLK_EQUALS
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_GREATER
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_QUESTION
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_AT

    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LBRACKET, 0}, // SDLK_LEFTBRACKET
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_BACKSLASH, 0}, // SDLK_BACKSLASH
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RBRACKET, 0}, // SDLK_RIGHTBRACKET
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_CARET
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_UNDERSCORE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_GRAVE, 0}, // SDLK_BACKQUOTE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_A, 0}, // SDLK_a
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_B, 0}, // SDLK_b
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_C, 0}, // SDLK_c
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_D, 0}, // SDLK_d
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_E, 0}, // SDLK_e
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F, 0}, // SDLK_f
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_G, 0}, // SDLK_g
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_H, 0}, // SDLK_h
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_I, 0}, // SDLK_i
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_J, 0}, // SDLK_j
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_K, 0}, // SDLK_k
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_L, 0}, // SDLK_l
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_M, 0}, // SDLK_m
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_N, 0}, // SDLK_n
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_O, 0}, // SDLK_o
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_P, 0}, // SDLK_p
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_Q, 0}, // SDLK_q
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_R, 0}, // SDLK_r
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_S, 0}, // SDLK_s
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_T, 0}, // SDLK_t
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_U, 0}, // SDLK_u
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_V, 0}, // SDLK_v
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_W, 0}, // SDLK_w
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_X, 0}, // SDLK_x
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_Y, 0}, // SDLK_y
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_Z, 0}, // SDLK_z
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_DELETE, 0}, // SDLK_DELETE

    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},

    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_0
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_1
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_2
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_3
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_4
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_5
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_6
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_7
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_8
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_9
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_10
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_11
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_12
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_13
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_14
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_15
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_16
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_17
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_18
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_19
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_20
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_21
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_22
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_23
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_24
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_25
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_26
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_27
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_28
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_29
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_30
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_31
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_32
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_33
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_34
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_35
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_36
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_37
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_38
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_39
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_40
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_41
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_42
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_43
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_44
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_45
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_46
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_47
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_48
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_49
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_50
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_51
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_52
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_53
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_54
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_55
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_56
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_57
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_58
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_59
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_60
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_61
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_62
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_63
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_64
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_65
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_66
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_67
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_68
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_69
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_70
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_71
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_72
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_73
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_74
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_75
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_76
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_77
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_78
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_79
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_80
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_81
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_82
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_83
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_84
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_85
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_86
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_87
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_88
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_89
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_90
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_91
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_92
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_93
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_94
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_WORLD_95

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_0, 0}, // SDLK_KP0
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_1, 0}, // SDLK_KP1
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_2, 0}, // SDLK_KP2
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_3, 0}, // SDLK_KP3
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_4, 0}, // SDLK_KP4
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_5, 0}, // SDLK_KP5
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_6, 0}, // SDLK_KP6
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_7, 0}, // SDLK_KP7
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_8, 0}, // SDLK_KP8
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_9, 0}, // SDLK_KP9
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_PERIOD, 0}, // SDLK_KP_PERIOD
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_DIVIDE, 0}, // SDLK_KP_DIVIDE
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_MULTIPLY, 0}, // SDLK_KP_MULTIPLY
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_MINUS, 0}, // SDLK_KP_MINUS
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_PLUS, 0}, // SDLK_KP_PLUS
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_KP_ENTER, 0}, // SDLK_KP_ENTER
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_KP_EQUALS

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_UP, 0}, // SDLK_UP
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_DOWN, 0}, // SDLK_DOWN
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RIGHT, 0}, // SDLK_RIGHT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LEFT, 0}, // SDLK_LEFT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_INSERT, 0}, // SDLK_INSERT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_HOME, 0}, // SDLK_HOME
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_END, 0}, // SDLK_END
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PAGEUP, 0}, // SDLK_PAGEUP
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PAGEDOWN, 0}, // SDLK_PAGEDOWN

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F1, 0}, // SDLK_F1
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F2, 0}, // SDLK_F2
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F3, 0}, // SDLK_F3
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F4, 0}, // SDLK_F4
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F5, 0}, // SDLK_F5
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F6, 0}, // SDLK_F6
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F7, 0}, // SDLK_F7
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F8, 0}, // SDLK_F8
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F9, 0}, // SDLK_F9
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F10, 0}, // SDLK_F10
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F11, 0}, // SDLK_F11
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_F12, 0}, // SDLK_F12

    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_F13
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_F14
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_F15

    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},
    {EMULATEDINPUT_NONE, 0, 0},

    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_NUMLOCK, 0}, // SDLK_NUMLOCK
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_CAPSLOCK, 0}, // SDLK_CAPSLOCK
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_SCROLLLOCK, 0}, // SDLK_SCROLLOCK
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RSHIFT, 0}, // SDLK_RSHIFT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LSHIFT, 0}, // SDLK_LSHIFT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RCTRL, 0}, // SDLK_RCTRL
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LCTRL, 0}, // SDLK_LCTRL
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_RALT, 0}, // SDLK_RALT
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_LALT, 0}, // SDLK_LALT
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_RMETA
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_LMETA
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_LSUPER
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_RSUPER
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_MODE
    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_COMPOSE

    {EMULATEDINPUT_NONE, 0, 0}, // SDLK_HELP
    {EMULATEDINPUT_KEYPRESS, EMULATEDKEYINDEX_PRINTSCREEN, 0}, // SDLK_PRINT

    // A few more SDL 1.2 keysyms follow, but are ignored
#endif    
};


const MappedInputEvent_T defaultJoyButtonMappings[] = {
    {EMULATEDINPUT_JOYBUTTONPRESS, 1, 0},
    {EMULATEDINPUT_JOYBUTTONPRESS, 2, 0},
    {EMULATEDINPUT_JOYBUTTONPRESS, 4, 0},
    {EMULATEDINPUT_JOYBUTTONPRESS, 8, 0},
};

const MappedInputEvent_T defaultJoyPAxisMappings[] = {
    {EMULATEDINPUT_JOYMOTION, 1, 0},
    {EMULATEDINPUT_JOYMOTION, 2, 0},
    {EMULATEDINPUT_JOYMOTION, 3, 0},
    {EMULATEDINPUT_JOYMOTION, 4, 0},
};

const MappedInputEvent_T defaultJoyNAxisMappings[] = {
    {EMULATEDINPUT_JOYMOTION, -1, 0},
    {EMULATEDINPUT_JOYMOTION, -2, 0},
    {EMULATEDINPUT_JOYMOTION, -3, 0},
    {EMULATEDINPUT_JOYMOTION, -4, 0},
};

const MappedInputEvent_T defaultFullScreenHandlerMapping = {EMULATEDINPUT_HANDLER, INPUTHANDLER_FULLSCREEN, 2};
const MappedInputEvent_T defaultCursorLockHandlerMapping = {EMULATEDINPUT_HANDLER, INPUTHANDLER_CAPTURECURSOR, 1};
const MappedInputEvent_T defaultQuitHandlerMapping = {EMULATEDINPUT_HANDLER, INPUTHANDLER_SHUTDOWN, 1};
//const MappedInputEvent_T defaultSaveInputMapsMapping = {EMULATEDINPUT_HANDLER, INPUTHANDLER_SAVEINPUTMAPPINGS, 1};
const MappedInputEvent_T defaultFirstModifierMapping = {EMULATEDINPUT_MODTOGGLE, 1, 0};
const MappedInputEvent_T defaultSecondModifierMapping = {EMULATEDINPUT_MODTOGGLE, 2, 0};

const int defaultKeyMappingsCount =
    (int)(sizeof(defaultKeyMappings) / sizeof(defaultKeyMappings[0]));
